title       = "openmeteo"
baseURL     = "https://openmeteo-cli.tamnd.com/"
description = "A command line for openmeteo."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/openmeteo-cli"
